### ISSUE TITLE
Add level ?

### ISSUE THREAD

**Issue by natcl** [vdemedes/syslog-serialize#1]
Would it be possible to add the Level information as described here ?
http://www.kiwisyslog.com/help/syslog/index.html?protocol_levels.htm

**Comment by vadimdemedes** [comment]
I don't have enough time for this one right now, so I'd appreciate a PR!

**Comment by natcl** [comment]
Closing this as level is handled by the Priority via this formula: Priority = Facility \* 8 + Level
